# Generated by Django 5.0.6 on 2024-05-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/headers/'),
        ),
    ]
