# Generated by Django 5.0.6 on 2024-05-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_header_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='header_pic',
        ),
    ]
