# Generated by Django 5.0.3 on 2024-04-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_likes_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='This is a short description of this post.', max_length=350),
        ),
    ]
