# Generated by Django 5.0.4 on 2024-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile_instagram_link_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='user', max_length=100, unique=True),
        ),
    ]
