# Generated by Django 5.0.4 on 2024-04-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
    ]
